[1;92mINFO [2024-04-20 17:25:03 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-06 12:12:16 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-07-06 12:12:16 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-06 12:12:16 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-06 12:12:16 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-07-06 12:12:18 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-07-06 12:12:18 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-06 12:12:18 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-06 12:12:18 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-06 12:12:18 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-07-06 12:12:18 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-07-06 12:12:19 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-07-06 12:12:19 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-07-06 12:12:19 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-07-06 12:12:19 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-06 12:12:19 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-06 12:12:20 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-06 12:12:22 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-07-06 12:12:22 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-06 12:12:22 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-06 12:12:22 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-06 12:12:22 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-06 12:12:22 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-06 12:12:23 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-06 12:12:23 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-06 12:12:23 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-06 12:12:23 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-06 12:12:23 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-06 12:12:23 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-06 12:12:23 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-06 12:12:23 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-07-06 12:12:27 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-06 12:13:00 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-06 12:13:00 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-06 12:13:01 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-06 12:13:01 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-06 12:13:01 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-06 12:13:01 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-06 12:13:01 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-06 12:13:01 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-06 12:13:01 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-06 12:13:01 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-06 12:13:01 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-06 12:13:01 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-07-06 12:13:04 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-08 09:13:06 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-07-08 09:13:06 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 09:13:06 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 09:13:06 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-07-08 09:13:08 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-07-08 09:13:08 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-08 09:13:08 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 09:13:08 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 09:13:08 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-07-08 09:13:08 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 09:13:08 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 09:13:08 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 09:13:08 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 09:13:08 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 09:13:08 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 09:13:09 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-07-08 09:13:09 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-08 09:13:09 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-07-08 09:13:09 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-07-08 09:13:09 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-07-08 09:13:09 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 09:13:09 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 09:13:09 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 09:13:10 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-07-08 09:13:10 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-08 09:13:10 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 09:13:10 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 09:13:11 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 09:13:11 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 09:13:12 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 09:13:12 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 09:13:12 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 09:13:12 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 09:13:12 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 09:13:13 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-08 09:13:13 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-08 09:13:13 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-07-08 09:13:37 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-08 09:13:57 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 09:13:57 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 09:13:57 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 09:13:57 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 09:13:57 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 09:13:57 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 09:13:57 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 09:13:57 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 09:13:57 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 09:13:58 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-08 09:13:58 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-08 09:13:58 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-07-08 09:14:12 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-08 09:14:21 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 09:14:21 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 09:14:22 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 09:14:22 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 09:14:22 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 09:14:22 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 09:14:22 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 09:14:22 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 09:14:22 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 09:14:23 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-08 09:14:23 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-08 09:14:23 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-07-08 09:14:36 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-08 11:31:15 - auth.py:82] - Start creating a new auth key on DC2[0m
[1;92mINFO [2024-07-08 11:31:15 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 11:31:15 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 11:31:15 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-07-08 11:31:17 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-07-08 11:31:17 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-08 11:31:17 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 11:31:17 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 11:31:17 - connection.py:54] - Connected! Production DC2 - IPv4[0m
[1;92mINFO [2024-07-08 11:31:17 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:291] - PingTask stopped[0m
[1;92mINFO [2024-07-08 11:31:18 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:315] - NetworkTask stopped[0m
[1;92mINFO [2024-07-08 11:31:18 - session.py:180] - Session stopped[0m
[1;92mINFO [2024-07-08 11:31:18 - auth.py:82] - Start creating a new auth key on DC4[0m
[1;92mINFO [2024-07-08 11:31:18 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 11:31:18 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 11:31:18 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 11:31:20 - auth.py:267] - Done auth key exchange: DhGenOk[0m
[1;92mINFO [2024-07-08 11:31:20 - connection.py:66] - Disconnected[0m
[1;92mINFO [2024-07-08 11:31:20 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 11:31:20 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 11:31:20 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 11:31:20 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 11:31:21 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 11:31:21 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 11:31:21 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 11:31:21 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 11:31:21 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 11:31:21 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-08 11:31:21 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-08 11:31:21 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;91mERROR [2024-07-08 11:31:31 - dispatcher.py:253] - Error -2 connecting to redis:6379. Name or service not known.[0m
Traceback (most recent call last):
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/connection.py", line 595, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/freeguy/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/freeguy/Desktop/project/vid-compress/app/plugins/start.py", line 9, in say_hello
    data = con.setting
  File "/home/freeguy/Desktop/project/vid-compress/app/utils/connection.py", line 32, in setting
    last_request_time = self.redis_client.get('last_request_time')
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/commands/core.py", line 1829, in get
    return self.execute_command("GET", name)
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/home/freeguy/.local/lib/python3.10/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
[1;92mINFO [2024-07-08 11:31:35 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-08 11:32:13 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 11:32:13 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 11:32:13 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 11:32:13 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 11:32:15 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 11:32:15 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 11:32:15 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 11:32:15 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 11:32:15 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 11:32:16 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-08 11:32:16 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-08 11:32:16 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;91mERROR [2024-07-08 11:32:20 - dispatcher.py:253] - '>' not supported between instances of 'float' and 'str'[0m
Traceback (most recent call last):
  File "/home/freeguy/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/freeguy/Desktop/project/vid-compress/app/plugins/start.py", line 9, in say_hello
    data = con.setting
  File "/home/freeguy/Desktop/project/vid-compress/app/utils/connection.py", line 34, in setting
    if last_request_time is None or current_time - float(last_request_time) > CACHE_TTL:
TypeError: '>' not supported between instances of 'float' and 'str'
[1;92mINFO [2024-07-08 11:32:38 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
[1;92mINFO [2024-07-08 11:32:40 - tcp.py:67] - Using proxy 127.0.0.1[0m
[1;92mINFO [2024-07-08 11:32:40 - connection.py:47] - Connecting...[0m
[1;92mINFO [2024-07-08 11:32:40 - connection.py:54] - Connected! Production DC4 - IPv4[0m
[1;92mINFO [2024-07-08 11:32:40 - session.py:294] - NetworkTask started[0m
[1;92mINFO [2024-07-08 11:32:40 - session.py:139] - Session initialized: Layer 158[0m
[1;92mINFO [2024-07-08 11:32:40 - session.py:140] - Device: CPython 3.10.12 - Pyrogram 2.0.106[0m
[1;92mINFO [2024-07-08 11:32:40 - session.py:141] - System: Linux 5.15.0-101-generic (en)[0m
[1;92mINFO [2024-07-08 11:32:40 - session.py:155] - Session started[0m
[1;92mINFO [2024-07-08 11:32:40 - session.py:272] - PingTask started[0m
[1;92mINFO [2024-07-08 11:32:41 - client.py:698] - [vid-compressbot] [LOAD] MessageHandler("say_hello") in group 0 from "plugins.start"[0m
[1;92mINFO [2024-07-08 11:32:41 - client.py:775] - [vid-compressbot] Successfully loaded 1 plugin from "plugins"[0m
[1;92mINFO [2024-07-08 11:32:41 - dispatcher.py:154] - Started 8 HandlerTasks[0m
[1;92mINFO [2024-07-08 11:32:47 - idle.py:75] - Stop signal received (SIGINT). Exiting...[0m
